# -*- coding: utf-8 -*-
"""plant_disease_model.keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTk-Bx7bksw3k8ZexcOPLlrFDR8CD-xX
"""

!git clone https://github.com/spMohanty/PlantVillage-Dataset.git

!ls PlantVillage-Dataset/raw/color | head

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

DATASET_PATH = "PlantVillage-Dataset/raw/color"

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_data = datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

val_data = datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    subset="validation"
)

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
output = Dense(train_data.num_classes, activation="softmax")(x)

model = Model(base_model.input, output)

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(
    train_data,
    validation_data=val_data,
    epochs=2
)

model.save("plant_disease_model.keras")

from google.colab import files
files.download("plant_disease_model.keras")

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.title("🌿 Plant Disease Detection")

model = tf.keras.models.load_model("plant_disease_model.keras")

CLASS_NAMES = list(model.predict(np.zeros((1,224,224,3))).shape)

uploaded_file = st.file_uploader("Upload leaf image", type=["jpg","png"])

if uploaded_file:
    img = Image.open(uploaded_file).resize((224,224))
    img = np.array(img)/255.0
    img = np.expand_dims(img, axis=0)

    pred = model.predict(img)
    st.success("Prediction complete!")

from google.colab import files
files.download("plant_disease_model.keras")